# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Milter
version:      0.06
version_from: lib/Mail/Milter.pm
installdirs:  site
requires:
    Sendmail::Milter:              0.18

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
